title: "Rahul's Portfolio"
description: "A showcase of my projects and skills"
url: "https://rahulbhandari18.github.io/"
theme: jekyll-theme-minimal
# Social Links
social:
  github: "https://github.com/RahulBhandari18"
  linkedin: "https://www.linkedin.com/in/rahulbhandari10/"

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Contact"
    url: /contact
